import pandas as pd


class CleanTweets:
    """
    This class takes twitter dataframe generated by extract_dataframe.py and clean it
    The class methods takes no other arguments and they all return a cleaned a cleaned dataset

    Arguments:
    -----------

    df= A twitter Dataset

    Returns:
    --------
    A dataframe
    """

    def __init__(self, df: pd.DataFrame):
        self.df = df
        print('Automation in Action...!!!')

    def drop_unwanted_column(self) -> pd.DataFrame:
        """
        remove rows that has column names. This error originated from
        the data retrieving.
        """
        unwanted_rows_index = self.df[self.df['retweet_count'] == 'retweet_count'].index
        self.df.drop(unwanted_rows_index, inplace=True)
        self.df = self.df[self.df['polarity'] != 'polarity']

        return self.df

    def drop_duplicate(self) -> pd.DataFrame:
        """
        drop duplicated rows
        """
        self.df = self.df.drop_duplicates()

        return self.df

    def convert_to_datetime(self) -> pd.DataFrame:
        """
        convert column to datetime
        """
        self.df['created_at'] = pd.to_datetime(self.df['created_at'], errors='coerce')

        self.df = self.df[self.df['created_at'] >= '2020-12-31']

        return self.df

    def convert_to_numbers(self) -> pd.DataFrame:
        """
        convert columns like polarity, subjectivity, retweet_count
        favorite_count etc to numbers
        """
        self.df['polarity'] = pd.to_numeric(self.df['polarity'], errors='coerce')
        self.df['retweet_count'] = pd.to_numeric(self.df['retweet_count'], errors='coerce')
        self.df['favorite_count'] = pd.to_numeric(self.df['favorite_count'], errors='coerce')

        return self.df

    def remove_non_english_tweets(self) -> pd.DataFrame:
        """
        remove non english tweets from lang
        """

        self.df = self.df.query("lang == 'en' ")

        return self.df


if __name__ == "__main__":
    tweet_df = pd.read_csv("processed_tweet_data.csv")
    cleaner = CleanTweets(tweet_df)


"""To use this class, use it's instance "cleaner" and call every needed method.
    eg.: cleaner.drop_duplicate() return a new df with duplicate rows removed"""