name: TwitterTests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest Twitter-Data-Analysis/tests/*
      